FROM openjdk:11.0.10-slim-buster AS builder
WORKDIR /src
ADD . /src
RUN ./gradlew clean bootJar

FROM openjdk:11.0.10-slim-buster
WORKDIR /app
COPY --from=builder /src/build/libs/*-0.0.1-SNAPSHOT.jar .
COPY Hotels.geojson ./Hotels.geojson
CMD exec java -jar *.jar
