version: '3.7'

volumes:
  rabbit-data:
  es_data:

networks:
  elastic:
    driver: bridge
    
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/tmp/localstack
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - PORT_WEB_UI=15672
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data2
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic
  elasticsearch-mapping-init:
        build:
          context: .
        links:
          - elasticsearch
        depends_on:
          -elasticsearch
      